Lab4/urls.py
#FILE INI BIKIN SENDIRI:)

from django.conf.urls import url
from django.urls import path
from . import views
from django.conf.urls.static import static

app_name = 'Lab4'

urlpatterns = [
	path('',views.home,name='home'),
	path('about',views.aboutme,name='aboutme'),
	path('forms',views.addform,name="forms"),
	path('schedules',views.objform,name='schedules'),
	path('delete',views.deletesched,name='delete')
] 

Story4/urls.py
from django.conf.urls import url, include
from django.urls import path, re_path, include
from django.contrib import admin

urlpatterns = [
	path('admin/', admin.site.urls),
    path('', include('Lab4.urls')),
    ]
	

Lab4/models.py
from django.db import models

# Create your models here.
class Entry(models.Model):
	activity = models.CharField(max_length=100)
	date = models.DateField()
	time = models.TimeField()
	place = models.CharField(max_length=100)
	category = models.CharField(max_length=100)

Lab4/forms.py
from django import forms
from .models import Entry

class Message_Form(forms.Form):
	date = forms.DateField(label='Date', required=True, widget=forms.DateInput(attrs={'type' : 'date'}))
	time = forms.TimeField(label='Time', required=True, widget=forms.TimeInput(attrs={'type' : 'time'}))
	place = forms.CharField(label='Place', required=True)
	activity = forms.CharField(label='Activity',required=True,max_length='25')
	category = forms.CharField(label='Category', required=True)

Lab4/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .forms import Message_Form
from .models import Entry

def home(request):
	return render(request, "Home.html", {})

def aboutme(request):
	return render(request, "AboutMe.html", {})

def contact(request):
	return render(request, "Registration.html", {})

def objform(request):
    response = {}
    sched = Entry.objects.all()
    response = {
        "schedules" : sched
    }
    return render(request, "Schedule.html", response) #render ke page schedule

def addform(request):
    form = Message_Form(request.POST or None)
    response = {}
    if(request.method == "POST"):
        if (form.is_valid()):
            activity = request.POST.get('activity')
            category = request.POST.get('category')
            date = request.POST.get('date')
            time = request.POST.get('time')
            place = request.POST.get('place')
            print(activity, category, date, time, place)

        
            entry = Entry(activity=activity, category=category,
                          date=date, time=time, place=place)
            entry.save()

            return redirect("/schedules") 
        else:
            return render(request, "Form.html", response)

    else:
        response['form'] = form
        return render(request, 'Form.html', response)

def deletesched(request):
    Entry.objects.all().delete()
    response = {}
    return render(request,'Schedule.html',response)

Lab4/templates/AboutMe.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'styles.css' %}" />
	{% include 'navbar.html' %}
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
	<div id="nav-placeholder">

	</div>
	<script>
		$(function(){
  			$("#nav-placeholder").load("navbar.html");});
  	</script>
	<div class="rowA">
		<div id="info">
			<div class="row-a">
					<img src="https://i.imgur.com/InhShND.png" width="130px" height="130px" class="img2">
					<h1><b>PERSONAL<br>INFORMATION</b></h1>
			</div>
		</div>
		<div id="bio">
			<p>
				Place of Birth: Jakarta<br>
				Date of Birth: January 5, 1999<br>
				Nationality: Indonesia<br>
				Address: Mutiara Depok Estate <br>
				Blok CA/3<br>
				Email: azzahraputri05@gmail.com<br>
				Phone: 0811 997 442<br>
			</p>
		</div>
	</div>

	<div class="rowB">
		<h3><i>"If it doesn't challenge you, it won't change you"</i></h3>
	</div>

	<div class="footer">
		<footer>
			<a href="#" class="fa fa-skype"></a>
			<a href="https://www.instagram.com/azzahrapr" class="fa fa-instagram" target="_blank"></a>
			<a href="https://www.twitter.com/azzhrapr" class="fa fa-twitter" target="_blank"></a>
			<a href="https://www.linkedin.com/in/azzahraptr/" class="fa fa-linkedin" target="_blank"></a>
		</footer>
	</div>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Lab4/templates/Form.html
<!DOCTYPE html>
<html>
<head>
	<title>Enter your details!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'styles.css' %}" />
	{% include 'navbar.html' %}</head>
<body>
	<div id="nav-placeholder">

	</div>
	<script>
		$(function(){
  			$("#nav-placeholder").load("navbar.html");});
	</script>

	<div class="container">
		<h2>Fill this form below!</h2>
		<form id="form" method="POST" action="{% url 'Lab4:forms'%}">
			{% csrf_token %}
			{{ form }}
	    <button type="submit" class="registerbtn" value="submit">Submit</button>
		</form>

	</div>

	<div class="footer">
		<footer>
			<a href="#" class="fa fa-skype"></a>
			<a href="https://www.instagram.com/azzahrapr" class="fa fa-instagram" target="_blank"></a>
			<a href="https://www.twitter.com/azzhrapr" class="fa fa-twitter" target="_blank"></a>
			<a href="https://www.linkedin.com/in/azzahraptr/" class="fa fa-linkedin" target="_blank"></a>
		</footer>
	</div>
	<br>
	<br>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Lab4/templates/Home.html
<!DOCTYPE html>
<html>
<head>
	<title>Home - Welcome to Jaja's Website!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'styles.css' %}" />
	{% include 'navbar.html' %}
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
	<div id="nav-placeholder">

	</div>
	<script>
		$(function(){
  			$("#nav-placeholder").load("navbar.html");});
	</script>
	<div class="row1">
		<div id="desc">
			<h1><b>AZZAHRA PUTRI RAMADHANTY</b></h1>
			<h2>Student of Information System</h2>
			<p>Have a big interest in web designing and programming. My favorite subjects <br> 
				are PPW and SDA. I want to develope my skill in HTML5, CSS, and Java.</p>
		</div>	
		<div id="foto">
			<img src="https://i.imgur.com/CZMmwPZ.png" width="200px" height="200px">
		</div>
		<div id="hello">
			<h1>Hello!</h1>
		</div>
	</div>

	<div class="row2">
		<div id="edu">
			<img src="https://i.imgur.com/CdEurkf.png" width="80px" height="80px" class="img">
			<h3><b>EDUCATION</b></h3>
			<div class="par">
				<p>
					- University of Indonesia<br>
					- SMAN 3 Depok<br>
					- SMPN 1 Depok<br>
					- SD Pemuda Bangsa
				</p>
			</div>
		</div>
		<div id="skills">
			<img src="https://i.imgur.com/CYWipCk.png" width="80px" height="80px" class="img">
			<h3><b>SKILLS</b></h3>
			<div class="par">
				<p>
					- Public Relation <br>
					- Leadership <br>
					- Python<br>
					- Java<br>
					- HTML5<br>
					- Microsoft Word<br>
					- Microsoft PowerPoint<br>
					- Adobe Photoshop<br>
					- English<br>
					- Korean<br>
					- Piano<br>
					- Traditional Dance<br>
				</p>
			</div>
		</div>
		<div id="exp">
			<img src="https://i.imgur.com/GS6nmOx.png" width="80px" height="80px" class="img">
			<h3><b>EXPERIENCE</b></h3>
			<div class="par">
				<p>
					<b>Organizational Experience<br></b>
					- Adkesma BEM Fasilkom UI<br>
					- Binari Fasilkom UI<br>
					- Mezzo Voices SMAN 3 Depok<br>
					<br>
					<b>Working Experience<br></b>
					- HRD of Fundraising COMPEST X 2018<br>
					- Head of Public Relations Wisgen 2018<br>
					- Vice Person of Fundraising PMB 2018<br>
					- Staff of Events OH Fasilkom 2018<br>
					- Staff of Bazaar&Food CGT 2018<br>
					- Staff of Public Relations Wisgan 2018<br>
					- Staff of Sponsorship Universiade UI 2017<br>
					- Staff of Public Relations Pemira<br>
					Fasilkom 2017<br>
				</p>
			</div>
		</div>
		<div id="ach">
			<img src="https://i.imgur.com/GdoCxPd.png" width="80px" height="80px" class="img">
			<h3><b>ACHIEVEMENTS</b></h3>
			<div class="par">
				<p>
					- Fasilkom's Contingent of Traditional Dance UIAW 2018<br>
					- National Science Olympiad <br>
					Participant Regency State 2014
					- 3rd Winner of National Grand Try Out by Yayasan Taruna Bangsa 2011<br>
				</p>
			</div>
		</div>
	</div>

	<div class="footer">
		<footer>
			<a href="#" class="fa fa-skype"></a>
			<a href="https://www.instagram.com/azzahrapr" class="fa fa-instagram" target="_blank"></a>
			<a href="https://www.twitter.com/azzhrapr" class="fa fa-twitter" target="_blank"></a>
			<a href="https://www.linkedin.com/in/azzahraptr/" class="fa fa-linkedin" target="_blank"></a>
		</footer>
	</div>

	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

Lab4/templates/Registration.html
<!DOCTYPE html>
<html>
<head>
	<title>Enter your details!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'styles.css' %}" />
	{% include 'navbar.html' %}
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>

<body>
	<div id="nav-placeholder">

	</div>
	<script>
		$(function(){
  			$("#nav-placeholder").load("navbar.html");});
	</script>
	<form action="/action_page.php">
	  <div class="container">
	    <h1>Register</h1>
	    <p>Please fill in this form to create an account.</p>
	    
	    <hr>

	    <label for="name"><b>Name</b></label>
	    <input type="text" placeholder="Enter Name" name="name" required><br>

	    <label for="birth"><b>Birth Date</b></label>
	    <input type="date" placeholder="Enter Birth Date" name="birth" required><br>
	    <!-- Safari doens't support input date type:( Open with chrome -->

	    <label for="email"><b>Email</b></label>
	    <input type="email" placeholder="Enter Email" name="email" required><br>

	    <label for="uname"><b>Username</b></label>
	    <input type="text" placeholder="Enter Username" name="uname" required><br>

	    <label for="psw"><b>Password</b></label>
	    <input type="password" placeholder="Enter Password" name="psw" required><br>

	    <label for="psw-repeat"><b>Confirm Password</b></label>
	    <input type="password" placeholder="Repeat Password" name="psw-repeat" required><br>

	    <hr>
	    
	    <p>By creating an account you agree to our <a href="#">Terms & Privacy</a>.</p>

	    <button type="submit" class="registerbtn" value="submit">Register</button>
	  </div>
	</form>
	<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
	<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>

</html>

Lab4/templates/Schedule.html
{% extends "base.html"%}
{% load static%}
{% block content %}
    <div id="nav-placeholder">

    </div>
  
    <div class="col">
        <div class="container">
        <h2><b>MY SCHEDULES</b></h2>
        <hr>
        <table style="width:100%">
            {% if schedules %}
                <tr>
                    <th>Activity</th>
                    <th>Category</th>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Place</th>
                </tr>
           	        {% for event in schedules %}
                        <tr>
   	                        <td>{{ event.activity }}</td>
                            <td>{{ event.category }}</td>
                            <td>{{ event.date }}</td> 
                            <td>{{ event.time }}</td>
                            <td>{{ event.place }}</td>
                        </tr>
                    {% endfor %}
                {% else %}
                    <h5>No schedule. Make a plan!</h5> 
                {% endif %}
            </table>
            <br>
            <div class="row d-flex align-items-center justify-content-center">
            <div class="col-sm-2">
            <a href="{% url 'Lab4:forms' %}">Create Event</a> 
        </div>
        <div class="col-sm-2">
            <a href="{% url 'Lab4:delete' %}">Reset Schedule</a>
        </div>
        </div>
    </div>
    </div>
    </div>
    
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
{% endblock %}

Lab4/templates/base.html
<!DOCTYPE html>
<html>
<head>
    {% load static %}
	<title>base</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	{% load staticfiles %}
	<link rel="stylesheet" href="{% static 'styles.css' %}" />
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
	{% include 'navbar.html' %}
</head>
<body>
	<script>
		$(function(){
  			$("#nav-placeholder").load("navbar.html");});
	</script>
	<div class="footer">
		<footer>
			<a href="#" class="fa fa-skype"></a>
			<a href="https://www.instagram.com/azzahrapr" class="fa fa-instagram" target="_blank"></a>
			<a href="https://www.twitter.com/azzhrapr" class="fa fa-twitter" target="_blank"></a>
			<a href="https://www.linkedin.com/in/azzahraptr/" class="fa fa-linkedin" target="_blank"></a>
		</footer>
	</div>
	{% block content %}
    {% endblock %}
</body>
</html>

Lab4/templates/navbar.html
<!DOCTYPE html>
<html>
<head>
	<title>Home - Welcome to Jaja's Website!</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
	<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
	<script src="https://code.jquery.com/jquery-1.10.2.js"></script>
</head>
<body>
	<nav class="topnav"> 
		<button type="button" onclick="alert('CV Downloaded!')">Download Resume</button>
		<a href="{% url 'Lab4:aboutme'%}">About Me</a>
		<a href="{% url 'Lab4:home'%}">Home</a>
		<a href="{% url 'Lab4:schedules'%}">Schedules</a>
	</nav>	
</body>
</html>